/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";

export default function Model(props: any) {
  //@ts-ignore
  const { nodes, materials } = useGLTF("models/purple_calendar.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.035}>
        <directionalLight
          name="Directional_Light"
          intensity={0.7}
          //@ts-ignore
          decay={2}
          position={[200, 300, 300]}
          rotation={[-0.506, 0.629, 0.756]}
        />
        <group name="calendar" position={[0, 6, 12.114]} scale={0.812}>
          <mesh
            name="2"
            castShadow
            receiveShadow
            geometry={nodes["2"].geometry}
            position={[-49.833, -55.469, 13.054]}
            rotation={[-0.088, 0, 0]}
          >
            <meshPhongMaterial
              color="#C8C8F1"
              shininess={10}
            ></meshPhongMaterial>
          </mesh>
          <mesh
            name="5"
            castShadow
            receiveShadow
            geometry={nodes["5"].geometry}
            position={[0.378, -55.469, 13.054]}
            rotation={[-0.088, 0, 0]}
          >
            <meshPhongMaterial
              color="#C8C8F1"
              shininess={10}
            ></meshPhongMaterial>
          </mesh>
          <mesh
            name="O"
            castShadow
            receiveShadow
            geometry={nodes.O.geometry}
            position={[-20.947, 20.358, 6.41]}
            rotation={[-0.091, 0, 0]}
          >
            <meshPhongMaterial
              color="#A1A0E6"
              shininess={-13}
            ></meshPhongMaterial>
          </mesh>
          <mesh
            name="C"
            castShadow
            receiveShadow
            geometry={nodes.C.geometry}
            position={[-3.865, 20.358, 6.41]}
            rotation={[-0.091, 0, 0]}
          >
            <meshPhongMaterial
              color="#A1A0E6"
              shininess={-13}
            ></meshPhongMaterial>
          </mesh>
          <mesh
            name="T"
            castShadow
            receiveShadow
            geometry={nodes.T.geometry}
            position={[12.119, 20.358, 6.41]}
            rotation={[-0.091, 0, 0]}
          >
            <meshPhongMaterial
              color="#A1A0E6"
              shininess={-13}
            ></meshPhongMaterial>
          </mesh>
          <mesh
            name="Torus_3"
            castShadow
            receiveShadow
            geometry={nodes.Torus_3.geometry}
            position={[37.102, 68.756, -3.033]}
            rotation={[-0.087, Math.PI / 2, 0]}
          >
            <meshPhongMaterial
              color="#666595"
              shininess={5}
            ></meshPhongMaterial>
          </mesh>
          <mesh
            name="Torus_2"
            castShadow
            receiveShadow
            geometry={nodes.Torus_2.geometry}
            position={[-36.483, 68.756, -3.033]}
            rotation={[-0.087, Math.PI / 2, 0]}
          >
            <meshPhongMaterial
              color="#666595"
              shininess={5}
            ></meshPhongMaterial>
          </mesh>
          <mesh
            name="Torus_3_1"
            castShadow
            receiveShadow
            geometry={nodes.Torus_3_1.geometry}
            position={[32.826, 68.756, -3.033]}
            rotation={[-0.087, Math.PI / 2, 0]}
          >
            <meshPhongMaterial
              color="#666595"
              shininess={5}
            ></meshPhongMaterial>
          </mesh>
          <mesh
            name="Torus"
            castShadow
            receiveShadow
            geometry={nodes.Torus.geometry}
            position={[-40.759, 68.756, -3.033]}
            rotation={[-0.087, Math.PI / 2, 0]}
          >
            <meshPhongMaterial
              color="#666595"
              shininess={5}
            ></meshPhongMaterial>
          </mesh>
          <mesh
            name="Rectangle_4"
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_4.geometry}
            position={[0, -6.632, -9.364]}
          >
            <meshPhongMaterial
              color="#7B77D3"
              shininess={3}
            ></meshPhongMaterial>
          </mesh>
          <mesh
            name="Rectangle_3"
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_3.geometry}
            position={[0, -6.874, -3.267]}
            rotation={[-0.03, 0, 0]}
          >
            <meshPhongMaterial
              color="#7B77D3"
              shininess={3}
            ></meshPhongMaterial>
          </mesh>
          <mesh
            name="Rectangle_2"
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_2.geometry}
            position={[0, -6.44, 4.596]}
            rotation={[-0.086, 0, 0]}
          >
            <meshPhongMaterial
              color="#7B77D3"
              shininess={3}
            ></meshPhongMaterial>
          </mesh>
        </group>

        <OrthographicCamera
          makeDefault={false}
          position={[-93.072, -103.918, 1000]}
        />
        <hemisphereLight
          name="Default Ambient Light"
          intensity={0.75}
          color="#eaeaea"
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/purple_calendar.gltf");
