// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.5 public/models/clock_03_copy.gltf
// */

// import React, { useRef } from "react";
// import { useGLTF, OrthographicCamera } from "@react-three/drei";

// export default function Clock(props: any) {
//   const { nodes, materials } = useGLTF("models/clock_03_copy.gltf");
//   return (
//     <group {...props} dispose={null}>
//       <group scale={0.01}>
//         <directionalLight
//           intensity={1}
//           decay={2}
//           rotation={[-0.902, 0.62, 1.141]}
//         />
//         <OrthographicCamera
//           makeDefault={false}
//           far={100000}
//           near={0}
//           position={[514.487, 472.36, 766.837]}
//           rotation={[-0.51, 0.556, 0.287]}
//         />
//         <mesh
//           geometry={nodes.numbers_2.geometry}
//           material={nodes.numbers_2.material}
//           position={[7.48, 95.69, 75.092]}
//           scale={[5.624, 6.474, 5.624]}
//         />
//         <mesh
//           geometry={nodes.buttons.geometry}
//           material={nodes.buttons.material}
//           position={[-0.001, 164.102, 62.142]}
//         />
//         <mesh
//           geometry={nodes.legs.geometry}
//           material={nodes.legs.material}
//           position={[-3.437, 21.87, -2.23]}
//         />
//         <mesh
//           geometry={nodes.whitescreen.geometry}
//           material={nodes.whitescreen.material}
//           position={[-4.449, 97.58, 16.206]}
//           rotation={[Math.PI / 2, 0, 0]}
//           scale={1.689}
//         />
//         <mesh
//           geometry={nodes.body.geometry}
//           material={nodes.body.material}
//           position={[-4.449, 97.184, -0.825]}
//           rotation={[Math.PI / 2, 0, 0]}
//           scale={1.689}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload("models/clock_03_copy.gltf");
