// /*
//   Auto-generated by Spline
// */

// import useSpline from "@splinetool/r3f-spline";
// import { OrthographicCamera } from "@react-three/drei";

// export default function Scene({ ...props }) {
//   const { nodes, materials } = useSpline(
//     "https://prod.spline.design/0tqlJ4P2F0ASj1XY/scene.splinecode"
//   );
//   return (
//     <>
//       <color attach="background" args={["#e6e6fe"]} />
//       <group {...props} dispose={null}>
//         <directionalLight
//           name="Directional Light"
//           castShadow
//           intensity={0.7}
//           shadow-mapSize-width={1024}
//           shadow-mapSize-height={1024}
//           shadow-camera-near={-10000}
//           shadow-camera-far={100000}
//           shadow-camera-left={-1250}
//           shadow-camera-right={1250}
//           shadow-camera-top={1250}
//           shadow-camera-bottom={-1250}
//           position={[200, 300, 300]}
//         />
//         <group name="calendar" position={[-93.07, -103.92, 12.11]} scale={0.81}>
//           <mesh
//             name="2"
//             geometry={nodes["2"].geometry}
//             material={materials["Mat 4"]}
//             castShadow
//             receiveShadow
//             position={[-49.83, -55.47, 13.05]}
//             rotation={[-0.09, 0, 0]}
//             scale={1}
//           />
//           <mesh
//             name="5"
//             geometry={nodes["5"].geometry}
//             material={materials["Mat 4"]}
//             castShadow
//             receiveShadow
//             position={[0.38, -55.47, 13.05]}
//             rotation={[-0.09, 0, 0]}
//             scale={1}
//           />
//           <mesh
//             name="O"
//             geometry={nodes.O.geometry}
//             material={materials["Mat 3"]}
//             castShadow
//             receiveShadow
//             position={[-20.95, 20.36, 6.41]}
//             rotation={[-0.09, 0, 0]}
//             scale={1}
//           />
//           <mesh
//             name="C"
//             geometry={nodes.C.geometry}
//             material={materials["Mat 3"]}
//             castShadow
//             receiveShadow
//             position={[-3.86, 20.36, 6.41]}
//             rotation={[-0.09, 0, 0]}
//             scale={1}
//           />
//           <mesh
//             name="T"
//             geometry={nodes.T.geometry}
//             material={materials["Mat 3"]}
//             castShadow
//             receiveShadow
//             position={[12.12, 20.36, 6.41]}
//             rotation={[-0.09, 0, 0]}
//             scale={1}
//           />
//           <mesh
//             name="Torus 3"
//             geometry={nodes["Torus 3"].geometry}
//             material={materials["Mat 1"]}
//             castShadow
//             receiveShadow
//             position={[37.1, 68.76, -3.03]}
//             rotation={[-0.09, Math.PI / 2, 0]}
//             scale={1}
//           />
//           <mesh
//             name="Torus 2"
//             geometry={nodes["Torus 2"].geometry}
//             material={materials["Mat 1"]}
//             castShadow
//             receiveShadow
//             position={[-36.48, 68.76, -3.03]}
//             rotation={[-0.09, Math.PI / 2, 0]}
//             scale={1}
//           />
//           <mesh
//             name="Torus 31"
//             geometry={nodes["Torus 31"].geometry}
//             material={materials["Mat 1"]}
//             castShadow
//             receiveShadow
//             position={[32.83, 68.76, -3.03]}
//             rotation={[-0.09, Math.PI / 2, 0]}
//             scale={1}
//           />
//           <mesh
//             name="Torus"
//             geometry={nodes.Torus.geometry}
//             material={materials["Mat 1"]}
//             castShadow
//             receiveShadow
//             position={[-40.76, 68.76, -3.03]}
//             rotation={[-0.09, Math.PI / 2, 0]}
//             scale={1}
//           />
//           <mesh
//             name="Rectangle 4"
//             geometry={nodes["Rectangle 4"].geometry}
//             material={materials["Mat 2"]}
//             castShadow
//             receiveShadow
//             position={[0, -6.63, -9.36]}
//           />
//           <mesh
//             name="Rectangle 3"
//             geometry={nodes["Rectangle 3"].geometry}
//             material={materials["Mat 2"]}
//             castShadow
//             receiveShadow
//             position={[0, -6.87, -3.27]}
//             rotation={[-0.03, 0, 0]}
//             scale={1}
//           />
//           <mesh
//             name="Rectangle 2"
//             geometry={nodes["Rectangle 2"].geometry}
//             material={materials["Mat 2"]}
//             castShadow
//             receiveShadow
//             position={[0, -6.44, 4.6]}
//             rotation={[-0.09, 0, 0]}
//             scale={1}
//           />
//         </group>
//         <OrthographicCamera
//           name="1"
//           makeDefault={true}
//           zoom={0.24}
//           far={100000}
//           near={-100000}
//           position={[-87.94, -105.16, 1000]}
//           rotation={[0, 0, 0]}
//         />
//         <hemisphereLight
//           name="Default Ambient Light"
//           intensity={0.75}
//           color="#eaeaea"
//         />
//       </group>
//     </>
//   );
// }
